# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-29 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechantorder',
            name='merchantId',
            field=models.CharField(default=None, max_length=20, verbose_name='商家id'),
        ),
    ]
