# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-29 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_mechantorder_merchantid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MechantOrder',
            new_name='MerchantOrder',
        ),
    ]
