# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-10 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180929_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantorder',
            name='number',
            field=models.IntegerField(default=1, verbose_name='预订房间数'),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='orderstatus',
            field=models.IntegerField(choices=[(1, '已支付未入住'), (2, '入住中'), (3, '已过期'), (0, '已取消')], default=1, verbose_name='订单状态'),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='roomtype',
            field=models.CharField(default=None, max_length=20, verbose_name='房间类型'),
        ),
    ]
