# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-10 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20181010_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantorder',
            name='roomtype',
            field=models.CharField(default='无', max_length=20, verbose_name='房间类型'),
        ),
    ]
