# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-08 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantId', models.CharField(max_length=30, verbose_name='商家id')),
                ('title', models.CharField(max_length=30, verbose_name='房间名')),
                ('picture', models.ImageField(null=True, upload_to='static/image/roomtype', verbose_name='房间图片')),
                ('acreage', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='建筑面积')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('Bedtype', models.CharField(max_length=30, verbose_name='床型')),
                ('window', models.CharField(max_length=30, verbose_name='窗户')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('facility', models.CharField(max_length=30, verbose_name='配套设施')),
                ('examine', models.IntegerField(choices=[(0, '审核中'), (1, '审核通过'), (2, '审核失败')], verbose_name='审核状态')),
                ('isActive', models.BooleanField(verbose_name='是否激活')),
            ],
        ),
    ]
