# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-08 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='isShow',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
    ]
