# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-28 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_user', models.CharField(max_length=30, verbose_name='酒店账户')),
                ('hotel_pwd', models.CharField(max_length=100, verbose_name='密码')),
                ('title', models.CharField(max_length=20, verbose_name='酒店名')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
        ),
        migrations.CreateModel(
            name='room_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.IntegerField(choices=[(0, '经济房'), (1, '一房一厅'), (2, '两房一厅'), (3, '无房')], verbose_name='房间类型')),
                ('room_sq', models.IntegerField(verbose_name='房间面积')),
                ('room_window', models.BooleanField(default=True, verbose_name='是否有窗')),
                ('room_pic1', models.ImageField(upload_to='./static/housetype/img/', verbose_name='图片1')),
                ('room_pic2', models.ImageField(upload_to='./static/housetype/img/', verbose_name='图片2')),
                ('room_pic3', models.ImageField(upload_to='./static/housetype/img/', verbose_name='图片3')),
                ('room_pic4', models.ImageField(upload_to='./static/housetype/img/', verbose_name='图片4')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否激活')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housetype.Hotel')),
            ],
        ),
    ]
