# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-28 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housetype', '0004_auto_20180928_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_message',
            name='room_pic1',
            field=models.ImageField(upload_to='static/housetype/img/room', verbose_name='图片1'),
        ),
        migrations.AlterField(
            model_name='room_message',
            name='room_pic2',
            field=models.ImageField(upload_to='static/housetype/img/room/', verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='room_message',
            name='room_pic3',
            field=models.ImageField(upload_to='static/housetype/img/room/', verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='room_message',
            name='room_pic4',
            field=models.ImageField(upload_to='static/housetype/img/room/', verbose_name='图片4'),
        ),
    ]
