# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-28 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housetype', '0005_auto_20180928_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='pic',
            field=models.ImageField(default='static/housetype/img/defa.jpg', upload_to='static/housetype/img/', verbose_name='展示图'),
        ),
    ]
